import { getSession } from "@/lib/auth";
import { portfolioState, type PortfolioState } from "@/lib/portfolio";
import { EmailDigest } from "@/components/EmailDigest";

export const dynamic = "force-dynamic";

export default async function DigestPage() {
  let s: PortfolioState;
  try {
    s = await portfolioState(getSession());
  } catch (err) {
    return (
      <div className="card p-8 text-center text-sm text-muted">
        Could not build the digest: {(err as Error).message}
      </div>
    );
  }

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold text-ink">State of the portfolio</h1>
          <p className="text-sm text-muted">
            Management year {s.year} ({s.calendarYear}) · {s.total} parcels · {s.totalHa} ha under 30-year management
          </p>
        </div>
        <EmailDigest />
      </div>

      {/* Headline stats */}
      <div className="grid grid-cols-2 gap-3.5 md:grid-cols-4">
        <Tile label="On track" value={s.onTrack} sub={`${s.pctTrack}% of portfolio`} color="#3B7D3C" />
        <Tile label="At risk" value={s.atRisk} sub={`${s.atRiskHa} ha off trajectory`} color="#8E5BB5" />
        <Tile label="Awaiting Earth observation" value={s.awaiting} sub="no baseline captured yet" color="#9C978B" />
        <Tile label="Mean condition" value={s.meanCondition.toFixed(2)} sub={`target ${s.target.toFixed(2)}`} />
      </div>

      {/* At-risk list */}
      <div className="card overflow-hidden">
        <div className="border-b border-line px-4 py-3">
          <div className="text-sm font-semibold text-ink">Parcels at risk, by severity</div>
          <div className="text-[11px] text-muted">These need a field survey to ground-truth the Earth observation signal.</div>
        </div>
        {s.atRiskList.length === 0 ? (
          <div className="px-4 py-10 text-center text-sm text-forest">No parcels are currently at risk.</div>
        ) : (
          <table className="w-full text-sm">
            <thead className="bg-panel text-left text-[10px] uppercase tracking-[0.07em] text-muted">
              <tr>
                <th className="px-4 py-2">Ref</th>
                <th className="px-4 py-2">Site</th>
                <th className="px-4 py-2">Habitat</th>
                <th className="px-4 py-2 text-right">Area</th>
                <th className="px-4 py-2 text-right">Gap</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-line2">
              {s.atRiskList.map((r) => (
                <tr key={r.id} className="hover:bg-panel">
                  <td className="px-4 py-2.5 text-[11px] tabular-nums text-muted">{r.code}</td>
                  <td className="px-4 py-2.5 font-medium text-ink">{r.name}</td>
                  <td className="px-4 py-2.5 text-muted">{r.habitat}</td>
                  <td className="px-4 py-2.5 text-right tabular-nums text-muted">{r.area} ha</td>
                  <td className="px-4 py-2.5 text-right font-semibold tabular-nums" style={{ color: "#8E5BB5" }}>
                    {r.gap.toFixed(2)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      <p className="text-xs text-muted">
        Generated by BioCoda. Earth observation condition is decision support; field verification is authoritative. Thirty years of habitat, on the record.
      </p>
    </div>
  );
}

function Tile({ label, value, sub, color }: { label: string; value: number | string; sub: string; color?: string }) {
  return (
    <div className="card px-[18px] pb-[15px] pt-[17px]">
      <div className="text-[10.5px] font-semibold uppercase tracking-[0.1em] text-muted">{label}</div>
      <div className="mt-1 text-[40px] font-bold leading-none tabular-nums" style={{ color: color ?? "#18301A", letterSpacing: "-0.02em" }}>
        {value}
      </div>
      <div className="mt-1.5 text-[11.5px] text-muted">{sub}</div>
    </div>
  );
}
