/**
 * Seed generator → SQL. Deterministic; safe to re-run.
 *
 *   pnpm --filter @biocoda/db seed:print   # preview to stdout
 *   pnpm --filter @biocoda/db seed:sql      # write sql/0003_seed.sql
 *
 * The generated SQL is mounted into the postgis container's init dir, so the
 * demo DB comes up fully populated with ~40 parcels of mixed trajectories.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  classify,
  observedConditionAt,
  requiredCurve,
  scoreToBand,
  MANAGEMENT_PERIOD_YEARS,
} from "@biocoda/shared";
import { MockMetricAdapter, DEMO_NOW } from "@biocoda/adapters";
import { seedParcels, parcelLookups, parcelProfile, TENANT_ID } from "./parcels.js";

const MS_PER_YEAR = 365.25 * 24 * 60 * 60 * 1000;
const NOW_ISO = DEMO_NOW.toISOString();

function q(s: string): string {
  return s.replace(/'/g, "''");
}
function geomSql(geojson: unknown): string {
  return `ST_SetSRID(ST_GeomFromGeoJSON('${q(JSON.stringify(geojson))}'), 4326)`;
}
function yearsBetween(fromIso: string, toIso: string): number {
  return (new Date(toIso).getTime() - new Date(fromIso).getTime()) / MS_PER_YEAR;
}

async function buildSql(): Promise<string> {
  const parcels = seedParcels();
  const { meta, baselines } = parcelLookups(parcels);
  const metric = new MockMetricAdapter(meta);

  const lines: string[] = [];
  lines.push("-- BioCoda seed: generated by packages/db/src/seed.ts. Do not edit by hand.");
  lines.push("BEGIN;");
  lines.push("");

  // Tenants (the responsible body owns the demo portfolio; others for context).
  lines.push("INSERT INTO tenant (id, name, type) VALUES");
  lines.push(
    [
      `('${TENANT_ID}', 'Natural Trust Responsible Body', 'responsible_body')`,
      `('lpa-downshire', 'Downshire County Council', 'lpa')`,
      `('dev-greenfield', 'Greenfield Developments Ltd', 'developer')`,
    ].join(",\n") + ";",
  );
  lines.push("");

  // Users: two field ecologists scoped to the responsible body's portfolio.
  lines.push("INSERT INTO app_user (id, tenant_id, role, name, email) VALUES");
  lines.push(
    [
      `('user-rb-1', '${TENANT_ID}', 'responsible_body', 'Priya Natarajan', 'priya@naturaltrust.example')`,
      `('user-eco-1', '${TENANT_ID}', 'ecologist', 'Tom Hardy', 'tom@fieldeco.example')`,
      `('user-eco-2', '${TENANT_ID}', 'ecologist', 'Sara Okafor', 'sara@fieldeco.example')`,
    ].join(",\n") + ";",
  );
  lines.push("");

  let conditionRows = 0;
  let atRisk = 0;

  for (const p of parcels) {
    const profile = parcelProfile(p.id);
    const base = await metric.baseline(p.metricRef);
    const baselineIso = baselines[p.id]!;
    const currentYear = Math.max(0, Math.floor(yearsBetween(baselineIso, NOW_ISO)));

    // parcel
    lines.push(
      `INSERT INTO parcel (id, tenant_id, name, habitat_type, metric_ref, geom, area_ha, baseline_date) VALUES ` +
        `('${p.id}', '${p.tenantId}', '${q(p.name)}', '${q(p.habitatType)}', '${p.metricRef}', ${geomSql(
          p.geom,
        )}, ${p.areaHa}, '${p.baselineDate}');`,
    );

    // target
    lines.push(
      `INSERT INTO target (id, parcel_id, baseline_condition, target_condition, baseline_units, target_units, by_year) VALUES ` +
        `('target-${p.id}', '${p.id}', '${base.baselineCondition}', '${base.targetCondition}', ${base.baselineUnits}, ${base.targetUnits}, ${base.byYear});`,
    );

    // EO condition series: quarterly from baseline to now.
    const start = new Date(baselineIso).getTime();
    const end = DEMO_NOW.getTime();
    const step = MS_PER_YEAR / 4;
    const values: string[] = [];
    for (let t = start; t <= end; t += step) {
      const iso = new Date(t).toISOString();
      const year = yearsBetween(baselineIso, iso);
      if (year < 0) continue;
      const v = Math.round(observedConditionAt(p.id, year) * 100) / 100;
      values.push(`('${p.id}', 'condition_score', ${v}, '${iso}', 'eo')`);
      conditionRows++;
    }
    if (values.length) {
      lines.push(
        `INSERT INTO condition_point (parcel_id, metric, value, captured_at, source) VALUES\n  ` +
          values.join(",\n  ") +
          ";",
      );
    }

    // Latest trajectory flag.
    const actual = observedConditionAt(p.id, currentYear);
    const { status, required, gap } = classify(
      {
        baselineCondition: profile.baselineCondition,
        targetCondition: profile.targetCondition,
        targetYear: profile.byYear,
      },
      currentYear,
      actual,
    );
    if (status === "at_risk") atRisk++;
    lines.push(
      `INSERT INTO trajectory_flag (parcel_id, status, year, actual, required, gap, detected_at) VALUES ` +
        `('${p.id}', '${status}', ${currentYear}, ${round2(actual)}, ${round2(required)}, ${round2(
          gap,
        )}, '${NOW_ISO}');`,
    );

    // An open survey task for at-risk parcels (seeds the ecologist worklist).
    if (status === "at_risk") {
      lines.push(
        `INSERT INTO survey_task (parcel_id, reason, status, created_at) VALUES ` +
          `('${p.id}', 'EO trajectory at risk: ${scoreToBand(actual)} vs required ${scoreToBand(
            required,
          )} (gap ${round2(gap)})', 'open', '${NOW_ISO}');`,
    );
    }
    lines.push("");
  }

  lines.push("COMMIT;");
  lines.push("");
  lines.push(
    `-- Summary: ${parcels.length} parcels, ${conditionRows} condition points, ${atRisk} at-risk (open survey tasks).`,
  );
  return lines.join("\n");
}

function round2(v: number): number {
  return Math.round(v * 100) / 100;
}

async function main() {
  const sql = await buildSql();
  const outFlag = process.argv.indexOf("--out");
  if (process.argv.includes("--print")) {
    process.stdout.write(sql + "\n");
    return;
  }
  if (outFlag !== -1) {
    const rel = process.argv[outFlag + 1] ?? "sql/0003_seed.sql";
    const __dirname = dirname(fileURLToPath(import.meta.url));
    const out = resolve(__dirname, "..", rel);
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, sql + "\n");
    process.stderr.write(`wrote ${out}\n`);
    return;
  }
  process.stdout.write(sql + "\n");
}

void main();
