import "server-only";
import { assessParcel } from "@biocoda/shared";
import { listParcels } from "./data.js";
import type { Session } from "./db.js";

/** The "current" management year the portfolio sits at (matches the dashboard default). */
export const CURRENT_YEAR = 9;
export const BASE_YEAR = 2025;
export const TARGET_SCORE = 3;

export interface AtRiskItem {
  id: string;
  name: string;
  code: string;
  habitat: string;
  area: number;
  gap: number;
}

export interface PortfolioState {
  year: number;
  calendarYear: number;
  total: number;
  onTrack: number;
  atRisk: number;
  awaiting: number;
  pctTrack: number;
  meanCondition: number;
  target: number;
  totalHa: number;
  atRiskHa: number;
  atRiskList: AtRiskItem[];
}

/** Compute the state of the portfolio at a management year. */
export async function portfolioState(
  session: Session,
  year: number = CURRENT_YEAR,
): Promise<PortfolioState> {
  const parcels = await listParcels(session);
  let onTrack = 0, atRisk = 0, awaiting = 0, sum = 0, scored = 0, totalHa = 0, atRiskHa = 0;
  const atRiskList: AtRiskItem[] = [];

  for (const p of parcels) {
    const a = assessParcel(p.id, year);
    totalHa += p.areaHa;
    if (a.kind === "awaiting") {
      awaiting++;
      continue;
    }
    sum += a.actual;
    scored++;
    if (a.kind === "risk") {
      atRisk++;
      atRiskHa += p.areaHa;
      atRiskList.push({ id: p.id, name: p.name, code: a.code, habitat: p.habitatType, area: p.areaHa, gap: a.gap });
    } else {
      onTrack++;
    }
  }
  atRiskList.sort((x, y) => x.gap - y.gap);

  return {
    year,
    calendarYear: BASE_YEAR + year,
    total: parcels.length,
    onTrack,
    atRisk,
    awaiting,
    pctTrack: parcels.length ? Math.round((onTrack / parcels.length) * 100) : 0,
    meanCondition: scored ? Math.round((sum / scored) * 100) / 100 : 0,
    target: TARGET_SCORE,
    totalHa: Math.round(totalHa * 10) / 10,
    atRiskHa: Math.round(atRiskHa),
    atRiskList,
  };
}

/** Plain-text + HTML digest body, used for the page and the email. */
export function digestHtml(s: PortfolioState): string {
  const rows = s.atRiskList
    .slice(0, 12)
    .map(
      (r) =>
        `<tr><td style="padding:6px 10px;border-bottom:1px solid #DCE5D7">${r.name}</td>` +
        `<td style="padding:6px 10px;border-bottom:1px solid #DCE5D7;color:#5E5A50">${r.habitat}</td>` +
        `<td style="padding:6px 10px;border-bottom:1px solid #DCE5D7;text-align:right;color:#8E5BB5">${r.gap.toFixed(2)}</td></tr>`,
    )
    .join("");
  return `
  <div style="font-family:Inter,Arial,sans-serif;color:#18301A;max-width:640px">
    <h2 style="margin:0 0 4px">BioCoda: state of the portfolio</h2>
    <p style="margin:0 0 16px;color:#5E5A50">Management year ${s.year} (${s.calendarYear}) across ${s.total} parcels, ${s.totalHa} ha.</p>
    <table style="border-collapse:collapse;margin-bottom:18px">
      <tr>
        <td style="padding:8px 16px 8px 0"><b style="color:#3B7D3C;font-size:22px">${s.onTrack}</b> on track</td>
        <td style="padding:8px 16px 8px 0"><b style="color:#8E5BB5;font-size:22px">${s.atRisk}</b> at risk</td>
        <td style="padding:8px 16px 8px 0"><b style="color:#9C978B;font-size:22px">${s.awaiting}</b> awaiting Earth observation</td>
        <td style="padding:8px 0"><b style="font-size:22px">${s.meanCondition.toFixed(2)}</b> mean condition / ${s.target.toFixed(2)}</td>
      </tr>
    </table>
    ${
      s.atRiskList.length
        ? `<h3 style="margin:0 0 6px">At-risk parcels (${s.atRiskHa} ha)</h3>
           <table style="border-collapse:collapse;width:100%;font-size:14px"><tbody>${rows}</tbody></table>`
        : `<p style="color:#3B7D3C">No parcels are currently at risk.</p>`
    }
    <p style="margin-top:18px;color:#5E5A50;font-size:12px">Generated by BioCoda. Thirty years of habitat, on the record.</p>
  </div>`;
}
