import type { ConditionBand } from "./condition.js";

/**
 * Deterministic per-parcel profile.
 *
 * Everything that needs to agree on a parcel's *story* (the DB seed, the EO
 * worker, and the mock EO adapter) derives it from this one function, keyed
 * only by `parcelId`. That keeps demos reproducible (build doc §1.4) and means
 * the seeded `target` row, the synthetic EO curve, and the trajectory verdict
 * can never drift apart.
 *
 * The synthetic EO curve itself (observed condition over time) is generated by
 * `observedConditionAt`, which is mirrored byte-for-byte in the Python worker
 * (apps/eo-worker/app/engine.py). Keep the two in sync.
 */

/** Stable 32-bit string hash (FNV-1a). Matches the worker's implementation. */
export function hashU32(s: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

export type ProfileKind =
  | "improving" // climbing on/above the required curve
  | "plateau" // improves then stalls below the rising requirement
  | "declining" // slips below the required curve over time
  | "stable_good"; // already good, maintained

const KINDS: ProfileKind[] = ["improving", "plateau", "declining", "stable_good"];

export interface ParcelProfile {
  kind: ProfileKind;
  baselineCondition: ConditionBand;
  targetCondition: ConditionBand;
  byYear: number;
}

const PROFILE_SPEC: Record<ProfileKind, Omit<ParcelProfile, "kind">> = {
  improving: { baselineCondition: "poor", targetCondition: "good", byYear: 12 },
  plateau: { baselineCondition: "poor", targetCondition: "good", byYear: 10 },
  declining: { baselineCondition: "moderate", targetCondition: "good", byYear: 15 },
  stable_good: { baselineCondition: "good", targetCondition: "good", byYear: 5 },
};

export function parcelProfile(parcelId: string): ParcelProfile {
  const kind = KINDS[hashU32(parcelId) % KINDS.length]!;
  return { kind, ...PROFILE_SPEC[kind] };
}

const SCORE: Record<ConditionBand, number> = { poor: 1, moderate: 2, good: 3 };

/**
 * Synthetic EO-estimated condition (0–3) for a parcel at management-period
 * `year`. Deterministic; the small wiggle imitates inter-survey EO noise.
 *
 * MUST stay identical to `observed_condition_at` in the Python worker.
 */
export function observedConditionAt(parcelId: string, year: number): number {
  const p = parcelProfile(parcelId);
  const b = SCORE[p.baselineCondition];
  const g = SCORE[p.targetCondition];
  const seed = hashU32(parcelId);
  // Deterministic noise in roughly [-0.05, 0.05].
  const wiggle = (Math.sin(year * 1.7 + (seed % 100) / 10) * 0.05);

  let base: number;
  switch (p.kind) {
    case "improving": {
      const frac = Math.min(1, year / p.byYear);
      base = b + (g - b) * frac * 1.02;
      break;
    }
    case "plateau": {
      const ceiling = b + (g - b) * 0.55; // stalls well short of target
      base = b + (ceiling - b) * Math.min(1, year / 6);
      break;
    }
    case "declining": {
      base = b - 0.06 * year; // steady slip
      break;
    }
    case "stable_good": {
      base = g - 0.05;
      break;
    }
  }
  return clamp(base + wiggle, 0, 3);
}

function clamp(v: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, v));
}
